# Generated by Django 3.2.6 on 2021-08-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Город')),
                ('logo', models.URLField(default='https://place-hold.it/100x60', verbose_name='Логотипчик')),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('employee_count', models.PositiveIntegerField(verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('picture', models.URLField(default='https://place-hold.it/100x60', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'специализация',
                'verbose_name_plural': 'специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Текст')),
                ('salary_min', models.PositiveIntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateField(verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='catalog.company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='catalog.specialty', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
            },
        ),
    ]
