# Generated by Django 3.2.6 on 2021-09-23 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Город')),
                ('logo', models.ImageField(upload_to='company_images', verbose_name='Логотипчик')),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('employee_count', models.PositiveIntegerField(verbose_name='Количество сотрудников')),
                (
                    'owner',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Владелец',
                    ),
                ),
            ],
            options={
                'verbose_name': 'компанию',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='speciality_images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'специализацию',
                'verbose_name_plural': 'специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Текст')),
                ('salary_min', models.PositiveIntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateField(verbose_name='Опубликовано')),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vacancies',
                        to='catalog.company',
                        verbose_name='Компания',
                    ),
                ),
                ('specialty',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='vacancies',
                     to='catalog.specialty',
                     verbose_name='Специализация',
                 ),
                 ),
            ],
            options={
                'verbose_name': 'вакансию',
                'verbose_name_plural': 'вакансии',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_in_search', 'Не ищу работу'),
                            ('consideration', 'Рассматриваю предложения'),
                            ('in_search', 'Ищу работу'),
                        ],
                        default='not_in_search',
                        max_length=255,
                        verbose_name='Готовность к работе'),
                ),
                ('salary', models.PositiveIntegerField(verbose_name='Вознаграждение')),
                (
                    'grade',
                    models.CharField(
                        choices=[
                            ('trainee', 'Стажер'),
                            ('junior', 'Джуниор'),
                            ('middle', 'Миддл'),
                            ('senior', 'Синьор'),
                            ('lead', 'Лид'),
                        ],
                        max_length=255,
                        verbose_name='Квалификация',
                    ),
                ),
                ('education', models.TextField(verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('portfolio', models.URLField(verbose_name='Портфолио')),
                (
                    'specialty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='resumes',
                        to='catalog.specialty',
                        verbose_name='Специализация',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=255, verbose_name='Имя')),
                ('written_phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('written_cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='applications',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
                (
                    'vacancy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='applications',
                        to='catalog.vacancy',
                        verbose_name='Вакансия',
                    ),
                ),
            ],
            options={
                'verbose_name': 'отклик',
                'verbose_name_plural': 'отклики',
            },
        ),
    ]
