# Generated by Django 3.2.6 on 2021-09-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='company_images', verbose_name='Логотипчик'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Владелец',
            ),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(null=True, upload_to='speciality_images', verbose_name='Картинка'),
        ),
    ]
