# Generated by Django 3.2.6 on 2021-09-10 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_auto_20210910_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Владелец',
            ),
        ),
    ]
