# Generated by Django 3.2.6 on 2021-09-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_company_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'отклик', 'verbose_name_plural': 'отклики'},
        ),
    ]
