# Generated by Django 3.2.6 on 2021-09-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_alter_application_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_in_search', 'Не ищу работу'),
                            ('consideration', 'Рассматриваю предложения'),
                            ('in_search', 'Ищу работу'),
                        ],
                        max_length=255,
                        verbose_name='Готовность к работе',
                    ),
                ),
                ('salary', models.PositiveIntegerField(verbose_name='Вознаграждение')),
                ('education', models.TextField(verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('portfolio', models.URLField(verbose_name='Портфолио')),
                (
                    'specialty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='resumes',
                        to='catalog.specialty',
                        verbose_name='Специализация',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
            },
        ),
    ]
