# Generated by Django 3.2.6 on 2021-09-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210921_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(
                choices=[
                    ('trainee', 'Стажер'),
                    ('junior', 'Джуниор'),
                    ('middle', 'Миддл'),
                    ('senior', 'Синьор'),
                    ('lead', 'Лид'),
                ],
                max_length=255,
                verbose_name='Квалификация',
            ),
        ),
    ]
